- hosts: localhost
  tasks:
    - name: Installing dependencies
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - mariadb-server
        - php7.3
        - php7.3-mysql
        - php-mbstring
        - php-zip
        - unzip
        - pwgen
        - php-json
        - memcached
        - software-properties-common
        - python-mysqldb
        - mariadb-client
        - mariadb-common
        - mariadb-server

    - name: Copy database dump to tmp directory
      copy: src=/root/aquarium-monitoring.sql dest=/tmp/aquarium-monitoring.sql

    - name: Create database
      mysql_db: name=aquarium-monitoring state=present login_user='root' login_password='wordpass'

    - name: Import data
      mysql_db: name=aquarium-monitoring state=import target=/tmp/aquarium-monitoring.sql login_user='root' login_password='wordpass'
  I